theme = "congo"
baseURL = "http://deprov447.tech"
languageCode = "en"
defaultContentLanguage = "en"

title = "Pen"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
enableRobotsTXT = true

[author]
  name = "deprov447"
  image = "https://i.imgur.com/ja5j1FL.jpg"
  links = [
      { email = "mailto:ac.10edu@gmail.com" },
      { github = "https://github.com/deprov447" },
      { linkedin = "https://www.linkedin.com/in/anubhavchoudhary-deprov447/" },
      { gitlab = "https://invent.kde.org/deprov" },
      { medium = "https://medium.com/@deprov447" },
  ]
