baseURL = "/"
languageCode = "en-us"
title = "deprov447"
publishDir = "docs"
theme="archie"
copyright = "© deprov447"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	customcss = ["css/text.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/deprov447"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Micro wins"
url = "/micro-wins"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5
